/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/hamburguesa.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.15, 0]} scale={[1.03, 0.74, 1.03]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['bread_outside._top.002']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.cheese} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials.meat} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_6.geometry} material={materials.side} />
        <mesh geometry={nodes.Cylinder_7.geometry} material={materials.onion_top} />
        <mesh geometry={nodes.Cylinder_8.geometry} material={materials['bread_outside._top']} />
        <mesh geometry={nodes.Cylinder_9.geometry} material={nodes.Cylinder_9.material} />
        <mesh geometry={nodes.Cylinder_10.geometry} material={nodes.Cylinder_10.material} />
        <mesh geometry={nodes.Cylinder_11.geometry} material={nodes.Cylinder_11.material} />
      </group>
      <group position={[2.21, -0.94, 0.24]} rotation={[0.01, -0.63, 1.56]} scale={[0.6, 0.6, 0.48]}>
        <mesh geometry={nodes.Cube073.geometry} material={materials.fries} />
        <mesh geometry={nodes.Cube073_1.geometry} material={nodes.Cube073_1.material} />
        <mesh geometry={nodes.Cube073_2.geometry} material={nodes.Cube073_2.material} />
        <mesh geometry={nodes.Cube073_3.geometry} material={nodes.Cube073_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/hamburguesa.glb')
